### ISSUE TITLE
Add Product

### ISSUE THREAD

**Issue by c20chin** [atimathong/onlineauction#14]

**Comment by atimathong** [comment]
@c20chin 

## **Feature specification**
1. Button to click "Add product"
2. Seller adds details regarding attributes in ER diagram
        - Please note that for simplicity, we can allow  1 picture upload per 1 product.
        - The pictures will go to our work directory instead of the SQL database
        -  However, we need to store the picture file name on SQL that exactly match the name of the pictures saved in our work directory.
        - Video tutorial: 
                  - https://www.youtube.com/watch?v=JaRq73y5MJk
                  - https://www.youtube.com/watch?v=onu3w8kqASU
3. Submit button : Product added to the items table
4. Product display as part of the existing products in store.
